"""
Backend analysis engine for Lythos SPWA.

Contains the core classes and functions for performing geotechnical
calculations based on the free-earth support method.

Revision notes (v0.2):
- Internal forces, anchor force and deflections are evaluated at the
  theoretical embedment D_req (moment equilibrium closes there); the
  design embedment D_design = round_up(1.2 * D_req) is reported only.
- Passive-side vertical stress now walks the real stratigraphy below the
  dredge line (previously the layer sequence was restarted at the dredge
  line, which was wrong for layered profiles).
- Free water above the dredge line on the passive side is now included.
- Mononobe-Okabe coefficients corrected (missing cos(delta+theta) term);
  (1 - kv) is applied to unit weights and surcharge.
- Deflection boundary conditions: cantilever -> rotation = deflection = 0
  at the theoretical toe; anchored -> deflection = 0 at lowest anchor and
  at the theoretical toe.
- Root finding with brentq (bracketed) instead of fsolve.
- Diagram grid includes every discontinuity (layer boundaries, water
  levels, dredge line, anchors) so trapezoidal integration is exact
  between breakpoints.
"""

from dataclasses import dataclass
from typing import Any, Dict, List, Optional, Tuple

import numpy as np
from scipy.integrate import cumulative_trapezoid, quad
from scipy.optimize import brentq

from .config import MM_PER_M, NUM_PLOT_POINTS

_EPS = 1e-6  # offset used to evaluate both sides of a discontinuity
DEFAULT_ANCHOR_STIFFNESS = 3000.0  # kN/m per m of wall (~4-strand, 15 m, s=2.5 m)


@dataclass
class SoilLayer:
    """Represents a single soil layer with its geotechnical properties."""
    name: str
    thickness: float
    gamma: float
    gamma_sat: float
    phi: float
    cohesion: float
    k_s: float = 20000.0   # horizontal subgrade reaction modulus (kN/m^3), beam-spring only
    k_s_method: str = "manual"   # "manual" | "menard" | "schmitt"
    E_M: float = 0.0             # Menard pressuremeter modulus (MPa), for menard/schmitt
    alpha: float = 0.33          # Menard rheological coefficient (sand 1/3, silt 1/2, clay 2/3)

    def get_design_properties(self, fs_phi: float, fs_c: float) -> 'SoilLayer':
        """Applies partial factors to tan(phi) and c."""
        phi_rad = np.radians(self.phi)
        if self.phi > 0 and fs_phi > 0:
            phi_d_rad = np.arctan(np.tan(phi_rad) / fs_phi)
        else:
            phi_d_rad = phi_rad
        c_d = self.cohesion / fs_c if fs_c > 0 else self.cohesion
        return SoilLayer(self.name, self.thickness, self.gamma, self.gamma_sat,
                         float(np.degrees(phi_d_rad)), c_d, self.k_s,
                         self.k_s_method, self.E_M, self.alpha)


class SoilProfile:
    """Manages the collection of soil layers and related calculations."""

    def __init__(self, layers_data: List[Dict[str, Any]], gamma_water: float):
        fields = SoilLayer.__dataclass_fields__
        self.layers = [SoilLayer(**{k: v for k, v in data.items() if k in fields})
                       for data in layers_data]
        self.gamma_water = gamma_water
        self._design_cache: Dict[Tuple[float, float], List[SoilLayer]] = {}

    # ------------------------------------------------------------------
    def layer_boundaries(self) -> List[float]:
        """Depths of the layer interfaces (excluding the surface)."""
        out, d = [], 0.0
        for layer in self.layers:
            d += layer.thickness
            out.append(d)
        return out

    def _design_layers(self, factors: Tuple[float, float]) -> List[SoilLayer]:
        if factors not in self._design_cache:
            self._design_cache[factors] = [
                layer.get_design_properties(*factors) for layer in self.layers]
        return self._design_cache[factors]

    def get_properties_at_depth(
            self, z: float, design: bool = False,
            factors: Optional[Tuple[float, float]] = None) -> SoilLayer:
        """Soil properties at depth z (last layer is extended downwards)."""
        layers = self._design_layers(factors) if design and factors else self.layers
        current_depth = 0.0
        for layer in layers:
            if current_depth + layer.thickness > z:
                return layer
            current_depth += layer.thickness
        return layers[-1]

    def total_stress_between(self, z_top: float, z: float,
                             water_level: float) -> float:
        """
        Total vertical stress at depth z generated by the soil between
        z_top and z, using the real stratigraphy (layers positioned from
        the ground surface). Soil above the water table uses gamma,
        below it gamma_sat. The last layer is extended downwards.
        """
        if z <= z_top:
            return 0.0
        sigma_v, layer_top = 0.0, 0.0
        for i, soil in enumerate(self.layers):
            is_last = (i == len(self.layers) - 1)
            layer_bottom = float('inf') if is_last else layer_top + soil.thickness
            a, b = max(layer_top, z_top), min(layer_bottom, z)
            if b > a:
                dry_h = max(0.0, min(b, water_level) - a)
                wet_h = (b - a) - dry_h
                sigma_v += soil.gamma * dry_h + soil.gamma_sat * wet_h
            layer_top = layer_bottom
            if layer_top >= z:
                break
        return sigma_v

    def calculate_effective_stress(
            self, z: float, water_level: float,
            z_top: float = 0.0) -> Tuple[float, float]:
        """
        Effective vertical stress and pore pressure at depth z, counting
        soil weight from z_top downwards (z_top = 0 for the retained side,
        z_top = dredge level for the passive side). water_level is
        measured from the ground surface.
        """
        if z < z_top:
            return 0.0, 0.0
        sigma_v = self.total_stress_between(z_top, z, water_level)
        pore_pressure = max(0.0, z - water_level) * self.gamma_water
        return sigma_v - pore_pressure, pore_pressure


class RetainingWall:
    """Holds all structural, geometric and load parameters."""

    def __init__(self, config: Dict[str, Any]):
        self._validate_inputs(config)
        self.config = config
        geo = config['geometry']
        loads = config['loads']
        opts = config['analysis_options']
        factors = config['factors']
        struct = config['structural_properties']

        self.h = geo['excavation_depth_H']
        self.beta = np.radians(geo['backfill_slope_beta'])
        self.alpha = np.radians(geo['dredge_line_slope_alpha'])
        self.delta = np.radians(geo['wall_friction_delta'])

        self.surcharge = loads['surcharge_load']
        self.hw_active = loads['water_level_active']
        self.hw_passive = loads['water_level_passive']

        self.anchors = self._parse_anchors(opts)
        self.anchor_depths = [a['depth'] for a in self.anchors]
        self.beam_spring_options = dict(opts.get('beam_spring', {}))
        self.is_seismic = opts['is_seismic']
        self.kh = opts.get('kh', 0.0) if self.is_seismic else 0.0
        self.kv = opts.get('kv', 0.0) if self.is_seismic else 0.0
        # seismic water effects (Kramer 1996 / Ebeling & Morrison 1992)
        self.submerged_theta = bool(opts.get('submerged_theta', True))
        self.hydrodynamic = bool(opts.get('hydrodynamic', True))

        self.e_modulus = struct['youngs_modulus_E']
        self._load_section_properties(config)
        self._calculate_allowable_stress(config)
        self.ei = self.e_modulus * self.i_moment

        self.fs_phi = factors['FS_friction_angle']
        self.fs_c = factors['FS_cohesion']
        self.fs_bending = factors['FS_bending']
        self.embedment_factor = factors['embedment_increase_factor']
        self.rounding_increment = factors.get('rounding_increment', 0.1)

        self.soil_profile = SoilProfile(
            config['soil_profile'], config['constants']['gamma_water'])

    def _load_section_properties(self, config: Dict[str, Any]):
        struct_props = config['structural_properties']
        manufacturer = struct_props['selected_manufacturer']
        selected_model = struct_props['selected_section_model']
        db = config.get('section_database', {})
        if manufacturer not in db:
            raise ValueError(f"Manufacturer '{manufacturer}' not in database.")
        section_data = next(
            (s for s in db[manufacturer] if s["model"] == selected_model), None)
        if section_data is None:
            raise ValueError(
                f"Section '{selected_model}' from '{manufacturer}' not in database.")
        self.i_moment = section_data['moment_of_inertia_I']
        self.w_modulus = section_data['section_modulus_W']
        self.selected_section_model = selected_model

    def _calculate_allowable_stress(self, config: Dict[str, Any]):
        struct_props = config['structural_properties']
        factors = config['factors']
        steel_grade = struct_props['selected_steel_grade']
        fy_yield = struct_props.get('steel_grades', {}).get(steel_grade)
        fs = factors.get('FS_bending')
        if fy_yield is None:
            raise ValueError(f"Steel grade '{steel_grade}' not in database.")
        if fs is None or fs <= 1.0:
            raise ValueError("'FS_bending' must be > 1.0.")
        self.f_allowable = fy_yield / fs
        self.selected_steel_grade = steel_grade
        self.fy_yield = fy_yield

    @staticmethod
    def _parse_anchors(opts: Dict[str, Any]) -> List[Dict[str, float]]:
        """
        Anchor definition (list 'anchors' of dicts; 'anchor_depths' floats
        are accepted for old project files):
            depth        m below the top of the wall
            angle        inclination below horizontal (deg), 0 = horizontal
            EA           axial stiffness of ONE anchor (kN)  [0 -> use 'stiffness']
            free_length  free (elastic) length of the tendon (m)
            spacing      horizontal spacing (m)
            prestress    lock-off load of ONE anchor, axial (kN)
            stiffness    horizontal spring stiffness per m of wall (kN/m/m),
                         used only when EA/free_length are not given
        Derived: 'stiffness' (kN/m/m) = EA/(L_free*s)*cos^2(angle),
                 'prestress_h' (kN/m) = P*cos(angle)/s
        """
        raw = opts.get('anchors')
        if raw is None:
            raw = [{'depth': d} for d in opts.get('anchor_depths', [])]
        anchors = []
        for a in raw:
            angle = float(a.get('angle', 0.0))
            ea = float(a.get('EA', 0.0))
            lf = float(a.get('free_length', 0.0))
            sp = float(a.get('spacing', 1.0)) or 1.0
            cos_a = float(np.cos(np.radians(angle)))
            if ea > 0 and lf > 0:
                k_axial = ea / (lf * sp)                 # kN/m per m of wall
                stiffness = k_axial * cos_a ** 2
            else:
                stiffness = float(a.get('stiffness', DEFAULT_ANCHOR_STIFFNESS))
            prestress = float(a.get('prestress', 0.0))    # kN per anchor (axial)
            anchors.append({
                'depth': float(a['depth']), 'angle': angle, 'EA': ea,
                'free_length': lf, 'spacing': sp, 'prestress': prestress,
                'stiffness': stiffness,
                'prestress_h': prestress * cos_a / sp,
            })
        return sorted(anchors, key=lambda a: a['depth'])

    @staticmethod
    def anchor_report(anchor: Dict[str, float], t_h: float) -> Dict[str, float]:
        """Axial force per anchor and vertical component per m from the
        horizontal force per m of wall t_h."""
        ang = np.radians(anchor['angle'])
        cos_a = float(np.cos(ang))
        return {
            'T_h': t_h,                                   # kN/m (horizontal)
            'T_axial': t_h / cos_a * anchor['spacing'],  # kN per anchor
            'V': t_h * float(np.tan(ang)),               # kN/m (vertical, downward on wall)
        }

    @staticmethod
    def _validate_inputs(config: Dict[str, Any]):
        h = config['geometry']['excavation_depth_H']
        if h <= 0:
            raise ValueError("Excavation depth H must be positive.")
        for a in RetainingWall._parse_anchors(config['analysis_options']):
            if not 0 <= a['depth'] < h:
                raise ValueError(
                    f"Anchor depth {a['depth']} m must be between 0 and H.")
            if a['stiffness'] <= 0 or a['prestress'] < 0:
                raise ValueError(
                    f"Anchor at {a['depth']} m: stiffness must be > 0 and "
                    "prestress >= 0.")
            if not 0 <= a['angle'] < 80:
                raise ValueError(
                    f"Anchor at {a['depth']} m: angle must be in [0, 80) deg.")
        loads = config['loads']
        if loads['water_level_active'] < 0 or loads['water_level_passive'] < 0:
            raise ValueError("Water levels must be >= 0 (measured from surface).")
        if loads['surcharge_load'] < 0:
            raise ValueError("Surcharge must be >= 0.")
        layers = config['soil_profile']
        if not layers:
            raise ValueError("At least one soil layer is required.")
        for layer in layers:
            if layer['thickness'] <= 0:
                raise ValueError(f"Layer '{layer['name']}': thickness must be > 0.")
            if layer['gamma'] <= 0 or layer['gamma_sat'] <= 0:
                raise ValueError(f"Layer '{layer['name']}': unit weights must be > 0.")
            if not 0 <= layer['phi'] < 90:
                raise ValueError(f"Layer '{layer['name']}': phi must be in [0, 90).")
            if layer['cohesion'] < 0:
                raise ValueError(f"Layer '{layer['name']}': cohesion must be >= 0.")
            if layer.get('k_s', 1.0) <= 0:
                raise ValueError(f"Layer '{layer['name']}': k_s must be > 0.")
            if layer.get('k_s_method', 'manual') != 'manual' and layer.get('E_M', 0.0) <= 0:
                raise ValueError(
                    f"Layer '{layer['name']}': E_M must be > 0 for the "
                    f"'{layer['k_s_method']}' k_s method.")
        opts = config['analysis_options']
        if opts['is_seismic'] and opts.get('kv', 0.0) >= 1.0:
            raise ValueError("kv must be < 1.")


class AnalysisEngine:
    """
    Free-earth support analysis: embedment depth, anchor force, internal
    forces and deflections.
    """

    def __init__(self, wall: RetainingWall):
        self.wall = wall
        self.d_required: Optional[float] = None
        self.d_design: Optional[float] = None
        self.t_anchors: Dict[float, float] = {}
        self.results: Dict[str, Any] = {}
        self.warnings: List[str] = []
        self._coeff_cache: Dict[Tuple[float, float], Tuple[float, float]] = {}
        self.is_cantilever = not bool(wall.anchor_depths)

    # ------------------------------------------------------------------
    # helpers
    # ------------------------------------------------------------------
    def _breakpoints(self, a: float, b: float,
                     include_anchors: bool = False) -> List[float]:
        """All discontinuities of the pressure functions inside (a, b)."""
        w = self.wall
        pts = {a, b}
        candidates = [w.h, w.hw_active, w.hw_passive]
        candidates += w.soil_profile.layer_boundaries()
        if include_anchors:
            candidates += w.anchor_depths
        for p in candidates:
            if a < p < b:
                pts.add(p)
        return sorted(pts)

    def _robust_quad(self, func, a: float, b: float) -> Tuple[float, float]:
        """Integrates func on [a, b], splitting at known discontinuities."""
        pts = self._breakpoints(a, b)
        total = 0.0
        for start, end in zip(pts[:-1], pts[1:]):
            if end > start:
                integral, _ = quad(func, start, end, limit=100)
                total += integral
        return total, 0.0

    def _get_pressure_coeffs(self, phi_deg: float,
                             theta_factor: float = 1.0) -> Tuple[float, float]:
        """
        Active (Ka) and passive (Kp) coefficients. Coulomb for static,
        Mononobe-Okabe for seismic conditions (vertical wall).
        theta_factor > 1 applies the submerged-backfill correction
        theta = atan(theta_factor * kh / (1 - kv)), theta_factor = gamma_sat / gamma'.
        """
        key = (round(phi_deg, 6), round(theta_factor, 6))
        if key in self._coeff_cache:
            return self._coeff_cache[key]
        phi, w = np.radians(phi_deg), self.wall
        delta, beta, alpha = w.delta, w.beta, w.alpha

        if w.is_seismic and w.kh > 0:
            theta = np.arctan(theta_factor * w.kh / (1.0 - w.kv))
            if theta >= phi - beta and phi > 0:
                msg = ("Mononobe-Okabe: seismic inertia angle theta >= phi - beta "
                       f"(theta={np.degrees(theta):.1f} deg, phi_d={phi_deg:.1f} deg); "
                       "K_AE is undefined and has been capped (sqrt term = 0).")
                if msg not in self.warnings:
                    self.warnings.append(msg)

            # K_AE
            num = np.sin(phi + delta) * np.sin(phi - theta - beta)
            den = np.cos(delta + theta) * np.cos(beta)
            root = np.sqrt(max(0.0, num) / den) if den > 0 else 0.0
            kae = (np.cos(phi - theta) ** 2 /
                   (np.cos(theta) * np.cos(delta + theta) * (1.0 + root) ** 2))

            # K_PE
            num = np.sin(phi + delta) * np.sin(phi - theta + alpha)
            den = np.cos(delta + theta) * np.cos(alpha)
            root = np.sqrt(max(0.0, num) / den) if den > 0 else 0.0
            if root >= 1.0:
                raise ValueError(
                    "Seismic passive coefficient is undefined for this "
                    "combination of phi, delta, alpha and kh.")
            kpe = (np.cos(phi - theta) ** 2 /
                   (np.cos(theta) * np.cos(delta + theta) * (1.0 - root) ** 2))
            self._coeff_cache[key] = (kae, kpe)
            return kae, kpe

        # Coulomb (static, vertical wall)
        num = np.sin(phi + delta) * np.sin(phi - beta)
        root = np.sqrt(max(0.0, num) / (np.cos(delta) * np.cos(beta)))
        ka = np.cos(phi) ** 2 / (np.cos(delta) * (1.0 + root) ** 2)

        num = np.sin(phi + delta) * np.sin(phi + alpha)
        root = np.sqrt(max(0.0, num) / (np.cos(delta) * np.cos(alpha)))
        if root >= 1.0:
            raise ValueError(
                "Passive coefficient is undefined for this combination of "
                "phi, delta and alpha.")
        kp = np.cos(phi) ** 2 / (np.cos(delta) * (1.0 - root) ** 2)
        self._coeff_cache[key] = (ka, kp)
        return ka, kp

    def _theta_factor(self, z: float, water_level: float, soil: SoilLayer) -> float:
        """gamma_sat / gamma' below the water table (restrained pore water),
        1.0 above it or when the correction is switched off."""
        w = self.wall
        if not (w.is_seismic and w.submerged_theta and z > water_level):
            return 1.0
        g_sub = soil.gamma_sat - w.soil_profile.gamma_water
        if g_sub <= 0.5:
            return 1.0
        return soil.gamma_sat / g_sub

    def hydrodynamic_pressure(self, z: float) -> float:
        """
        Westergaard (1933) hydrodynamic pressure of the free water standing
        in front of the wall (between the passive water level and the
        dredge line): p = 7/8 * kh * gamma_w * sqrt(H_w * y). It acts as a
        driving load (water pulls away from the wall on the outward swing).
        """
        w = self.wall
        if not (w.is_seismic and w.hydrodynamic and w.kh > 0):
            return 0.0
        hw_free = w.h - w.hw_passive
        if hw_free <= 0 or z < w.hw_passive or z > w.h:
            return 0.0
        y = z - w.hw_passive
        return 7.0 / 8.0 * w.kh * w.soil_profile.gamma_water * np.sqrt(hw_free * y)

    def _calculate_pressure_at_depth(self, z: float) -> Dict[str, float]:
        """Active and passive pressures (earth, water, total) at depth z."""
        w = self.wall
        factors = (w.fs_phi, w.fs_c)
        kv_factor = (1.0 - w.kv) if w.is_seismic else 1.0

        # --- retained (active) side -----------------------------------
        soil_a = w.soil_profile.get_properties_at_depth(z, True, factors)
        sig_v_eff, u_act = w.soil_profile.calculate_effective_stress(
            z, w.hw_active)
        ka, _ = self._get_pressure_coeffs(
            soil_a.phi, self._theta_factor(z, w.hw_active, soil_a))
        p_earth_act = max(
            0.0, ka * kv_factor * (sig_v_eff + w.surcharge)
            - 2.0 * soil_a.cohesion * np.sqrt(ka))
        p_hydro = self.hydrodynamic_pressure(z)
        p_total_act = p_earth_act + u_act + p_hydro

        # --- excavation (passive) side --------------------------------
        # Free water in front of the wall acts at every depth below the
        # passive water level, even above the dredge line.
        u_pass = max(0.0, z - w.hw_passive) * w.soil_profile.gamma_water
        p_earth_pass = 0.0
        if z > w.h:
            soil_p = w.soil_profile.get_properties_at_depth(z, True, factors)
            sig_v_eff_pass, _ = w.soil_profile.calculate_effective_stress(
                z, w.hw_passive, z_top=w.h)
            _, kp = self._get_pressure_coeffs(
                soil_p.phi, self._theta_factor(z, w.hw_passive, soil_p))
            p_earth_pass = max(
                0.0, kp * kv_factor * sig_v_eff_pass
                + 2.0 * soil_p.cohesion * np.sqrt(kp))
        p_total_pass = p_earth_pass + u_pass

        return {
            'active': p_total_act, 'passive': p_total_pass,
            'earth_active': p_earth_act, 'earth_passive': p_earth_pass,
            'water_active': u_act, 'water_passive': u_pass,
            'hydrodynamic': p_hydro
        }

    def _net_pressure(self, z: float) -> float:
        p = self._calculate_pressure_at_depth(z)
        return p['active'] - p['passive']

    # ------------------------------------------------------------------
    # equilibrium
    # ------------------------------------------------------------------
    def _moment_balance_equation(self, depth: float) -> float:
        """
        Net moment of the pressures about the reference point (toe for a
        cantilever, lowest anchor for an anchored wall). Root -> D_req.
        """
        w = self.wall
        if self.is_cantilever:
            ref = w.h + depth
            arm = lambda z: ref - z          # positive above the toe
        else:
            ref = w.anchor_depths[-1]
            arm = lambda z: z - ref          # positive below the anchor
        # Sign convention: driving (active) moment positive, so the
        # function is positive for small D and decreases with D.
        integrand = lambda z: self._net_pressure(z) * arm(z)
        m_net, _ = self._robust_quad(integrand, 0.0, w.h + depth)
        return m_net

    def _solve_embedment(self) -> float:
        """Bracketed root search for the theoretical embedment depth."""
        w = self.wall
        lo = 1e-3
        f_lo = self._moment_balance_equation(lo)
        if f_lo <= 0:
            if self.is_cantilever:
                raise RuntimeError(
                    "No net driving moment at zero embedment: check the loads "
                    "and water levels (water in front of the wall above the "
                    "retained water level?).")
            raise RuntimeError(
                "Free-earth support assumption not satisfied: the wall above "
                "the lowest anchor would rotate the toe into the retained soil "
                "(anchor too close to the dredge line for this excavation "
                "depth). Raise the anchor or increase H.")
        hi = max(0.5 * w.h, 0.5)
        for _ in range(12):
            if self._moment_balance_equation(hi) < 0:
                break
            hi *= 1.6
        else:
            raise RuntimeError(
                "Solver for embedment depth failed: no equilibrium found up "
                f"to D = {hi:.1f} m. Check soil strength / water levels.")
        return brentq(self._moment_balance_equation, lo, hi,
                      xtol=1e-6, rtol=1e-8, maxiter=200)

    def run(self):
        """Runs the complete analysis."""
        self.d_required = self._solve_embedment()
        self.d_design = float(np.ceil(
            self.d_required * self.wall.embedment_factor /
            self.wall.rounding_increment) * self.wall.rounding_increment)

        if not self.is_cantilever:
            self._calculate_anchor_forces()

        self._calculate_diagrams()
        self._perform_stress_check()
        self._perform_deflection_check()
        self._perform_vertical_check(self.t_anchors)
        self.results['anchor_report'] = {
            a['depth']: RetainingWall.anchor_report(a, self.t_anchors.get(a['depth'], 0.0))
            for a in self.wall.anchors}
        self.results['warnings'] = list(self.warnings)

    def vertical_resistance(self, length: float) -> float:
        """
        Indicative vertical (skin friction) resistance of the embedded part
        of the wall: integral over both faces of the limit earth pressures
        times tan(delta) below the dredge line. No end bearing, no
        partial factors beyond those already in the pressures.
        """
        w = self.wall
        tan_d = float(np.tan(w.delta))
        if tan_d <= 0 or length <= w.h:
            return 0.0
        f, _ = self._robust_quad(
            lambda z: (self._calculate_pressure_at_depth(z)['earth_active'] +
                       self._calculate_pressure_at_depth(z)['earth_passive']) * tan_d,
            w.h, length)
        return float(f)

    def _perform_vertical_check(self, t_anchors: Dict[float, float],
                                results: Optional[Dict[str, Any]] = None,
                                length: Optional[float] = None):
        """Vertical component of the anchor forces vs. skin friction (indicative)."""
        res = self.results if results is None else results
        w = self.wall
        v_load = sum(RetainingWall.anchor_report(a, t_anchors.get(a['depth'], 0.0))['V']
                     for a in w.anchors)
        v_res = self.vertical_resistance(
            length if length is not None else w.h + (self.d_design or 0.0))
        if v_load <= 1e-9:
            status = "N/A"
        else:
            status = "OK" if v_res >= v_load else "NOT OK - VERTICAL CAPACITY EXCEEDED!"
        res.update({'vertical_load': float(v_load), 'vertical_resistance': v_res,
                    'vertical_status': status})

    def _calculate_anchor_forces(self):
        """
        Anchor force from horizontal equilibrium at the THEORETICAL
        embedment D_req (consistent with the moment equilibrium).
        """
        w = self.wall
        total_length = w.h + self.d_required
        f_active, _ = self._robust_quad(
            lambda z: self._calculate_pressure_at_depth(z)['active'], 0.0, total_length)
        f_passive, _ = self._robust_quad(
            lambda z: self._calculate_pressure_at_depth(z)['passive'], 0.0, total_length)
        t_total = f_active - f_passive
        n = len(w.anchor_depths)

        if n == 1:
            self.t_anchors[w.anchor_depths[0]] = t_total
            return

        # Multi-anchor: simplified tributary-area distribution. NOTE: the
        # free-earth method is statically determinate for ONE anchor only;
        # for several anchors this distribution does not satisfy moment
        # equilibrium exactly and a beam-on-springs model should be used.
        midpoints = [(w.anchor_depths[i] + w.anchor_depths[i + 1]) / 2
                     for i in range(n - 1)]
        boundaries = [0.0] + midpoints + [total_length]
        area_forces = [
            self._robust_quad(self._net_pressure, boundaries[i], boundaries[i + 1])[0]
            for i in range(n)]
        positive = sum(f for f in area_forces if f > 0)
        for i, depth in enumerate(w.anchor_depths):
            self.t_anchors[depth] = (max(0.0, area_forces[i]) / positive * t_total
                                     if positive > 0 else t_total / n)

    # ------------------------------------------------------------------
    # diagrams
    # ------------------------------------------------------------------
    def _diagram_grid(self, length: float) -> np.ndarray:
        """Uniform grid plus both sides of every discontinuity."""
        z = np.linspace(0.0, length, NUM_PLOT_POINTS)
        extra = []
        for p in self._breakpoints(0.0, length, include_anchors=True):
            if 0.0 < p < length:
                extra += [p - _EPS, p, p + _EPS]
        return np.unique(np.concatenate([z, np.array(extra)]))

    def _calculate_diagrams(self):
        """
        Shear, moment, rotation and deflection along the wall, evaluated
        over the theoretical length H + D_req.
        """
        w = self.wall
        length = w.h + self.d_required
        z = self._diagram_grid(length)
        p_data = [self._calculate_pressure_at_depth(zi) for zi in z]
        net_p = np.array([p['active'] - p['passive'] for p in p_data])

        # Shear (positive = net active load accumulated from the top)
        v = cumulative_trapezoid(net_p, x=z, initial=0.0)
        for depth, force in sorted(self.t_anchors.items()):
            v[z >= depth] -= force

        # Moment
        m = cumulative_trapezoid(v, x=z, initial=0.0)

        # Curvature -> rotation -> deflection with proper boundary conditions
        curvature = m / w.ei if w.ei > 0 else np.zeros_like(m)
        r_raw = cumulative_trapezoid(curvature, x=z, initial=0.0)
        if self.is_cantilever:
            # Fixity assumed at the theoretical toe: rot(L) = defl(L) = 0
            r = r_raw - r_raw[-1]
            d = cumulative_trapezoid(r, x=z, initial=0.0)
            d -= d[-1]
        else:
            # Simple supports: defl(lowest anchor) = 0 and defl(L) = 0
            d_raw = cumulative_trapezoid(r_raw, x=z, initial=0.0)
            z_a = w.anchor_depths[-1]
            d_a = np.interp(z_a, z, d_raw)
            c = -(d_raw[-1] - d_a) / (length - z_a)
            r = r_raw + c
            d = d_raw + c * z - (d_a + c * z_a)

        imax = int(np.argmax(np.abs(d)))
        self.results = {
            'z_vals': z, 'net_pressure': net_p, 'shear': v, 'moment': m,
            'rotation': r, 'deflection': d,
            'p_max': float(np.max(net_p)), 'p_min': float(np.min(net_p)),
            'v_max': float(np.max(v)), 'v_min': float(np.min(v)),
            'm_max': float(np.max(m)), 'm_min': float(np.min(m)),
            'rot_max': float(np.max(r)), 'rot_min': float(np.min(r)),
            'delta_max': float(d[imax]),
            'toe_shear': float(v[-1]),      # cantilever: toe reaction R
            'toe_moment': float(m[-1]),     # should be ~0 (closure check)
            'earth_pressure_active': np.array([p['earth_active'] for p in p_data]),
            'earth_pressure_passive': np.array([p['earth_passive'] for p in p_data]),
            'water_pressure_active': np.array([p['water_active'] for p in p_data]),
            'water_pressure_passive': np.array([p['water_passive'] for p in p_data]),
            'hydrodynamic_pressure': np.array([p['hydrodynamic'] for p in p_data]),
        }
        self.results['rot_max_abs'] = max(abs(self.results['rot_max']),
                                          abs(self.results['rot_min']))

    def _perform_stress_check(self):
        m_max_abs = max(abs(self.results['m_max']), abs(self.results['m_min']))
        actual_stress = (m_max_abs / self.wall.w_modulus
                         if self.wall.w_modulus > 1e-9 else float('inf'))
        status = "OK" if actual_stress <= self.wall.f_allowable \
            else "NOT OK - STRESS EXCEEDED!"
        self.results.update({
            'm_max_abs': m_max_abs,
            'actual_stress': actual_stress,
            'stress_check_status': status
        })

    def _perform_deflection_check(self):
        delta_max_abs_mm = abs(self.results['delta_max'] * MM_PER_M)
        selected_code = self.wall.config['analysis_options']['deflection_check_code']
        divisor = self.wall.config['deflection_codes'].get(selected_code)
        if divisor is None:
            status, allowable_mm = "N/A", float('inf')
        else:
            allowable_mm = (self.wall.h / divisor) * MM_PER_M
            status = "OK" if delta_max_abs_mm <= allowable_mm \
                else "NOT OK - DEFLECTION EXCEEDED!"
        self.results.update({
            'deflection_check_status': status,
            'allowable_deflection': allowable_mm,
            'actual_max_deflection': delta_max_abs_mm
        })
